gapp/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
	url(r'^$', IndexView.as_view(), name='index'),
]

gmaps/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^gapp/', include('gapp.urls', namespace='gapp')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

gapp/models.py
from __future__ import unicode_literals

from django.db import models
from geoposition.fields import GeopositionField

class Country(models.Model):
	name = models.CharField(max_length=100, null=False, blank=False)

	def __unicode__(self):
		return self.name


class PointOfInterest(models.Model):
	name = models.CharField(max_length=50)
	address = models.CharField(max_length=100)
	position = GeopositionField()
	country = models.ForeignKey(Country, blank=True, null=True)

	def __unicode__(self):
		return self.name

gapp/forms.py
from django.forms import ModelForm
from .models import PointOfInterest


class PointOfInterestForm(ModelForm):

    class Meta:
        model = PointOfInterest
        fields = ['address', 'position']

gapp/views.py
import json
from django.shortcuts import render
from django.views.generic import View
from .forms import PointOfInterestForm
from .models import PointOfInterest, Country
from django.http import HttpResponse


class IndexView(View):
	template_name = 'gapp/map.html'

	def get(self, request, *args, **kwargs):
		data = PointOfInterest.objects.all()[0]
		form = PointOfInterestForm(instance=data)
		zone = PointOfInterest.objects.all()
		options = Country.objects.all()
		name_list = PointOfInterest.objects.values_list("pk", "address", "position")
		name_list_json = json.dumps(list(name_list))
		return render(request, self.template_name, {'name_list_json': name_list_json, 'options': options, 'form': form, 'data': data, 'zone':zone})
		
	def post(self, request, *args, **kwargs):
		select_id = request.POST['id']
		country = Country.objects.get(id=int(select_id))
		print select_id
		print country.name
		if country.name == '--all--':
			zone = PointOfInterest.objects.values_list("pk", "address", "position")
		else:
			zone = PointOfInterest.objects.filter(country=country).values_list("pk", "address", "position")
		data = json.dumps(list(zone))
		return HttpResponse(data, content_type="application/json")

templates/gapp/easy_map.html
<!--html>

{% load easy_maps_tags %}
<body>
   <h2>{{ address }}</h2>
   {% easy_map address 200 200 5 %}
   <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
   <form method="POST" action="">{% csrf_token %}
      {{ form.media }}
      {{ form.as_p }}
   </form>
</body>
</html-->

templates/gapp/map.html
<!DOCTYPE html>
{% load staticfiles %}
<html> 
<head> 
  <meta http-equiv="content-type" content="text/html; charset=UTF-8" /> 
  <title>Google Maps Multiple Markers</title> 
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="http://maps.google.com/maps/api/js?sensor=false" type="text/javascript"></script>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
</head> 

<body>
  <div id="map" style="width: 500px; height: 500px;"></div><br>

   <form class ="select_option" action="" method="post">{% csrf_token %}
		<select name="locations" onchange="showLocation(this.value)">
		     
		    {% for option in options%}
		       <option value="{{ option.id }}">{{ option.name }}</option>
		    {% endfor %}
			
		</select>
   </form>

  <!--img id="img" src="{% static "images/marker.png" %}" alt="markerimage" /-->


 <script type="text/javascript">
    
    function initialize() {
	    var mapDiv = document.getElementById('map');
	    map = new google.maps.Map(mapDiv, {
	      center: new google.maps.LatLng(48.208174,16.373819),
	      zoom: 8,
	      mapTypeId: google.maps.MapTypeId.ROADMAP
	    });
	    var arr = {{ name_list_json|safe }};
	    // for(i=0;i<arr.length;i++){
	    // 	// arr[i][2]=arr[i][2].split(',')
	    // 	console.log((arr[i][2][0]));
	    // }
        google.maps.event.addListenerOnce(map, 'tilesloaded', addMarkers(arr));
    }

    function addMarkers(zone) {
    	   var bounds = new google.maps.LatLngBounds();

    	   for(i=0;i<zone.length;i++){
    	   	  zone[i][2]=zone[i][2].split(',')
    	   	  // console.log(zone[i][2][1])
    	   	  var point = new google.maps.LatLng(zone[i][2][0], zone[i][2][1]);
		        // var image = "{% static 'images/marker.png' %}"
		        var marker = new google.maps.Marker({
		        position: point,
		        map: map,
		        // icon: image,
		       title: zone[i][1],
		       draggable: false,
		      });

		      bounds.extend(marker.position);

		      google.maps.event.addListener(marker, 'click', function() {
		        this['infowindow'].open(map, this);
		      });

    	    }
    	  
		  // {% for mark in zone %}
		  //   var point = new google.maps.LatLng({{mark.position.latitude}},{{mark.position.longitude}});
		  //       // var image = "{% static 'images/marker.png' %}"
		  //       var marker = new google.maps.Marker({
		  //       position: point,
		  //       map: map,
		  //       // icon: image,
		  //      title: '{{ mark.address }}',
		  //      draggable: false,
		  //   });

		  //   bounds.extend(marker.position);

		  //   google.maps.event.addListener(marker, 'click', function() {
		  //       this['infowindow'].open(map, this);
		  //   });

		  //   {% endfor %} 
		    map.setCenter(bounds.getCenter());
            map.fitBounds(bounds);
    }

    google.maps.event.addDomListener(window, 'load', initialize);

    function showLocation(str) {

    	$.ajax({
        url: "{% url 'gapp:index' %}",
        type: "POST",
        data: {
        	id: str,
        	csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
        },
        success: function(data) {
        	// console.log("success");
        	// google.maps.event.addDomListener(window, 'load');
        	alert("option changed");
        	console.log(data);
        	addMarkers(data)

        }});
	}

  </script>  
</body>
</html>